version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask-app
    restart: always
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx-flask
    restart: always
    ports:
      - "80:80"